### ISSUE TITLE
Failed to launch theme

### ISSUE THREAD

**Issue by mistrysiddh** [Yukuro/hugo-theme-shell#1]
![image](https://user-images.githubusercontent.com/25217451/126263351-94e4254a-ab60-41ef-bb34-3e034e893139.png)
I tried to install the theme but it giving me an error of
```
TOCSS: failed to transform "sass/default.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.
```
and I tried to upgrade my Hugo also but it is on the latest version  also I saw in your theme that there is no option for creating new post

**Comment by Yukuro** [comment]
- This theme requires the latest and **extended** version of Hugo.
- To create and display a new post
  1. Use the hugo command to create a post. i.e. `hugo new post/hello.md`
  2. Enter the path to the post in `config.toml` > `Params.Tree` > `files`. 
  i.e. `files = [ ["Sample", "/post/hello.md"] ]`

  Note: In the markdown file you created, make sure that `draft` in front matter is not set to true, or that the `hugo server` command has the `-D` option.

**Comment by mistrysiddh** [comment]
![image](https://user-images.githubusercontent.com/25217451/126275748-3380b4e3-322f-4d6b-a8f2-37a915d53bf1.png)
its on latest version

**Comment by Yukuro** [comment]
From your screenshot, it looks like you are running the normal version, not the extended version of Hugo.

If you are running the extended version,  you should see a screen similar to the one below.

![image](https://user-images.githubusercontent.com/15343476/126283076-d31ce26b-04bd-4efa-97b0-dc82a4326cff.png)

**Comment by mistrysiddh** [comment]
thank you it's working properly

**Comment by mistrysiddh** [comment]
and will this work with netlify hosting i already have my site working on netlify [https://www.mistrysiddh.tk](https://www.mistrysiddh.tk)

**Comment by mistrysiddh** [comment]
![image](https://user-images.githubusercontent.com/25217451/126291023-9213d470-c11d-44ce-8224-4192107b965b.png)
post not found when i created

> * This theme requires the latest and **extended** version of Hugo.
> * To create and display a new post
>   
>   1. Use the hugo command to create a post. i.e. `hugo new post/hello.md`
>   2. Enter the path to the post in `config.toml` > `Params.Tree` > `files`.
>      i.e. `files = [ ["Sample", "/post/hello.md"] ]`
>   
>   Note: In the markdown file you created, make sure that `draft` in front matter is not set to true, or that the `hugo server` command has the `-D` option.

**Comment by Yukuro** [comment]
The actual URL to the post is `localhost:1313/post/wellcome`, not `localhost:1313/post/wellcome.md`.
(If you write `"/post/wellcome.md"` in the `files` variable, the link in the index page will be automatically converted to `/post/wellcome/`)

If you change the baseURL in config.toml and add netlify.toml, it will work with Netlify.

In fact, the example of this theme works with Netlify.
This is the repository for the example site: https://github.com/Yukuro/hugo-theme-shell-example

**Comment by mistrysiddh** [comment]
ok so I assume that this theme will have a proper page for the post in the future, I will be waiting for it
