### ISSUE TITLE
Add a guide for customizing the theme

### ISSUE THREAD

**Issue by hhmacedo** [Yukuro/hugo-theme-shell#13]
It would be amazing if you could make a small guide teaching how to add more content (like another cat file at the end, or another tree between the cat and the tree), what files should be edited and how.

Thank you in advance, it is a really simple and nice theme.

**Comment by Yukuro** [comment]
In the current implementation, using the same command more than twice requires a radical redefinition of config.toml and many file changes.
Therefore, it may be difficult to create a guide right now.

However, I will add it to one of the feature requests.

**Comment by iEscapedVim** [comment]
> 
> 
> In the current implementation, using the same command more than twice requires a radical redefinition of config.toml and many file changes. Therefore, it may be difficult to create a guide right now.
> 
> However, I will add it to one of the feature requests.

bro, it wasn't that hard like you were acting like it's very big to deal to customize it. I only know HTML and some CSS I mainly work with WordPress but all you have to do was follow the damn train CJ!! lol sorry, all you had to do what point me to the direction and I could have taken care of it I am a very fast learner not like haven't already, took me about 30 minutes but anyway Thanks, for this beautiful creation. I hope you don't mind If I use it btw what language is it in the index.html file? I customized it but still don't know lol.. 

![image](https://user-images.githubusercontent.com/32537564/139540668-c2c10dfd-a664-4da0-94cd-d23739342ea2.png)

Edit Here's the final version ;) 

![image](https://user-images.githubusercontent.com/32537564/139544695-798c53a9-c2bd-46ea-b4ae-01dd8014f1c7.png)

**Comment by Yukuro** [comment]
index.html is written using the [Hugo Template](https://gohugo.io/templates/).

I've written a guide to customizing the terminal [here](https://github.com/Yukuro/hugo-theme-shell/blob/master/docs/customize_terminal/customize_terminal.md).
I'm hoping to rewrite the terminal customization using Hugo's features(i.e. shortcodes), and this may change in future updates.

**Comment by blazingstarz** [comment]
> > In the current implementation, using the same command more than twice requires a radical redefinition of config.toml and many file changes. Therefore, it may be difficult to create a guide right now.
> > However, I will add it to one of the feature requests.
> 
> bro, it wasn't that hard like you were acting like it's very big to deal to customize it. I only know HTML and some CSS I mainly work with WordPress but all you have to do was follow the damn train CJ!! lol sorry, all you had to do what point me to the direction and I could have taken care of it I am a very fast learner not like haven't already, took me about 30 minutes but anyway Thanks, for this beautiful creation. I hope you don't mind If I use it btw what language is it in the index.html file? I customized it but still don't know lol..
> 
> ![image](https://user-images.githubusercontent.com/32537564/139540668-c2c10dfd-a664-4da0-94cd-d23739342ea2.png)
> 
> Edit Here's the final version ;)
> 
> ![image](https://user-images.githubusercontent.com/32537564/139544695-798c53a9-c2bd-46ea-b4ae-01dd8014f1c7.png)

Your terminal page looks great. Can you show the source on how to make this modification to the theme? Having some difficulty to create a new tree section even after following the guide. Thanks!

**Comment by iEscapedVim** [comment]
> > > In the current implementation, using the same command more than twice requires a radical redefinition of config.toml and many file changes. Therefore, it may be difficult to create a guide right now.
> > > However, I will add it to one of the feature requests.
> > 
> > 
> > bro, it wasn't that hard like you were acting like it's very big to deal to customize it. I only know HTML and some CSS I mainly work with WordPress but all you have to do was follow the damn train CJ!! lol sorry, all you had to do what point me to the direction and I could have taken care of it I am a very fast learner not like haven't already, took me about 30 minutes but anyway Thanks, for this beautiful creation. I hope you don't mind If I use it btw what language is it in the index.html file? I customized it but still don't know lol..
> > ![image](https://user-images.githubusercontent.com/32537564/139540668-c2c10dfd-a664-4da0-94cd-d23739342ea2.png)
> > Edit Here's the final version ;)
> > ![image](https://user-images.githubusercontent.com/32537564/139544695-798c53a9-c2bd-46ea-b4ae-01dd8014f1c7.png)
> 
> Your terminal page looks great. Can you show the source on how to make this modification to the theme? Having some difficulty to create a new tree section even after following the guide. Thanks!

sent you an invite to the repo you can download and compare to your code. :)
