### ISSUE TITLE
<meta charset="UTF-8"> not set in index.html

### ISSUE THREAD

**Issue by dash042** [Yukuro/hugo-theme-shell#15]
I am getting the following output for "tree ./links"

./links/
â”œâ”€â”€  Link_1
â””â”€â”€  Link_2

Deployment via Github Repo and Azure Static Web App

Error occurs in Chrome, Brave & Edge (no others tested)

It displays correctly when running locally...

**Comment by Yukuro** [comment]
I was able to reproduce the same issue with azure static web app.
And I solved the problem with https://github.com/Yukuro/hugo-theme-shell/commit/89aa746262131b461ed439eb288e757e54ff842f.

If the problem is still not solved, please reopen
