### ISSUE TITLE
Feature request: support Markdown in description

### ISSUE THREAD

**Issue by colorchestra** [Yukuro/hugo-theme-shell#3]
Hi, thank you for this great looking theme!

It would be great if I could use Markdown in the description. Since this is the first thing people will read on my site, I'd like to be able to use bold text, italics etc. Maybe it would make sense to read the content of that field from a regular .md file / a Hugo post in the content directory, or maybe there's another way to make this field interpret Markdown.

Thank you!

**Comment by Yukuro** [comment]
That's a good idea.

**Comment by Yukuro** [comment]
By specifying a .md file as "description" in config.toml, it is now possible to use .md files.

See README.md and config/_default/config.toml for details.
![Screenshot from 2021-07-27 18-37-54](https://user-images.githubusercontent.com/15343476/127134986-08a6c29c-1b76-4512-9d20-6d58c906356d.png)

**Comment by colorchestra** [comment]
Dang, that was quick! Thanks so much @Yukuro !
