### ISSUE TITLE
Deploy on Netlify feature

### ISSUE THREAD

**Issue by DSDV** [Yukuro/hugo-theme-shell#35]
Hi, 
since the demo page is running on netlify i guess there is a way to get it working on their platform. 
there is a way to get a "deploy on netlify" button like here: https://templates.netlify.com/tags/hugo/

for new users like me the whole process is pretty daunting. so such a button would be really nice ( : 

(maybe i am just stupid but i am at my 3rd attempt right now to get a fresh page with shell theme and netlify cms working :/ )

with kind regards

**Comment by Yukuro** [comment]
Added `Deploy to Netlify` button in the README.md at https://github.com/Yukuro/hugo-theme-shell/commit/84c99c0f629bf3bb59f9b340dcf1f3a9e154a011
