### ISSUE TITLE
0 delay in pages

### ISSUE THREAD

**Issue by p1xxxel** [Yukuro/hugo-theme-shell#4]
Hey I really like this theme and was wondering is it possible to disable typing animation in blog pages while keeping it in the main page because it can be annoying to wait for the typing to finish if it is a long blog.

I tried setting delay to 0 but that did not change anything.

**Comment by Yukuro** [comment]
Typing animation can now be disabled by setting `actibityDelay` ( or `terminalDelay` ) to 0 in config.toml.

See the README.md for details.

![Peek 2021-07-30 17-37](https://user-images.githubusercontent.com/15343476/127626268-b58f454d-5511-4b6d-b10c-1e2c2f8761a2.gif)
