### ISSUE TITLE
Text colours are gone

### ISSUE THREAD

**Issue by Nick-Caris** [Yukuro/hugo-theme-shell#46]
**Describe the bug**
It seems that since the newest version "schemes" don't work properly. It only changes the background and not the text

**To Reproduce**
Build Hugo with peaceiris/actions-hugo

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38264134/224358670-423491ec-1f4c-4b46-9efe-864a90abf827.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 111.0.5563.64

**Additional context**
`[Params]
# Note: This is for the meta description, which is different from the "description" displayed in the terminal.
description = "40K custom forge world"
baseURL = "https://nick-caris.github.io/"

[Params.Terminal]
# Note: color scheme
# Note: You can choose between
# Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "shell-retro"]
# Note: If you want to use the Goph theme, set it to "goph" (See README.md)
scheme = "Molokai"

# Note: in terminal
# [userName]@[pcName]:~/$ cd [workDir]
# [userName]@[pcName]:~/[workDir]$ cat [profile]
#
# [description]
#
# Note: if you set Params.Tree > use = true
# [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
# ./[folderName]/
# ...
# Note: result of the tree command
userName = "Scribe#1312"
pcName = "Terminal"
workDir = "ForgeWorlds"
profile = "Malleaton"

# Note: speed at which text is displayed on the terminal
# Note: if set to 0, typing animation will be disabled
# Note:
# Note: if you want to enable Mathjax, you need to set it to 0
# Note: and set "math: true" at front matter in your Markdown file
ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

# Note: speed at which text is displayed on the activity pages
# Note: if set to 0, typing animation will be disabled
# Note:
# Note: if you want to enable Mathjax, you need to set it to 0
# Note: and set "math: true" at front matter in your Markdown file
titleDelay = 0 # title speed : "title" in front matter
contentDelay = 0 # content speed : content in .md file

# activityDelay = 5 : deprecated

description = """
    Malleaton, also known as the "The broken forge" is an Imperial Forge World of the Adeptus Mechanicus that is located in....
  """

# Note: If you want to use a Markdown file, you can use the following
# description = "/description.md"
# Note: and put the description.md in /content/description.md

[Params.Tree]
use = true
folderName = "Malleaton"
# Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
files = [
    ["Goverment", "/post/goverment.md"],
    ["Colours", "/post/colours.md"],
    ["History", "/post/history.md"],
    ["Geography", "/post/geography.md"],
    ["Manufactoria Capabilities", "/post/some-activity.md"],
]`

**Comment by Yukuro** [comment]
Thank you for your report.
I am aware of this issue and have corrected it in d643b39 .

You can either recreate the site or type the following command to correct the problem.
```bash
git submodule update --remote
```
