### ISSUE TITLE
Typing effect is present throughout entire page

### ISSUE THREAD

**Issue by TechnologyClassroom** [Yukuro/hugo-theme-shell#5]
Cool demo!  When using the terminal, the PS1 and stdout are nearly instantaneous and would not be typed.  It would be cool if only the commands had the typing effect.  This would also greatly speed up the page load times.

**Comment by Yukuro** [comment]
Hi.

I was thinking I should do the same thing to get closer to a real terminal.
However, the current implementation is fundamentally incapable of controlling the display order. I believe this will require a major change to improve this and may take some time to implement.

**Comment by adrianmace** [comment]
Yep, I was showing this to a few friends and they pointed out a similar thing about the use of `cat` where it would just instantly dump the entire contents of the file to screen unless you had a very slow terminal / buffer.

I love the typing effect of the commands, but the rest should be relatively static imho. 

Overall great theme! Love it! [Moved my personal portfolio](https://adrianmace.com/) over to it for a while to see how it goes.

**Comment by Yukuro** [comment]
Hi.

hugo-theme-shell now supports partial typing animation.
You can adjust the speed of each effect by setting the `/(ps1|stdout|command|title|content)Delay/` in config.toml.
Here is [example](https://hugo-theme-shell.netlify.app/).

I'm closing this issue, but if you have any feedback, please reopen this issue or create another one.

**Comment by TechnologyClassroom** [comment]
This looks great!  Good job!
