### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by joaopedromattos** [Yukuro/hugo-theme-shell#6]
Amazing template! A cool feature would be Latex syntax support to markdown files. Once again, thanks for the demo!

**Comment by Yukuro** [comment]
Latex syntax is now partially supported.

For several reasons, it is not possible to use the Latex syntax with typing animation enabled (see #8 for details).

To enable Latex syntax
1. set `terminalDelay` or `activityDelay` in config.toml to 0
2. set `math: true` in the front matter of the Markdown file
3. write a Markdown file like a [gist](https://gist.githubusercontent.com/Yukuro/6e6e3744c1d3c8fa2ef4ef96b162a0fd/raw/c9b51a8b3b4efea298d6c61e2ecd5d57f9964e9a/mathjaxExample.md)
